# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5ynxlaxK7JV9PNbU30lxWpT-SbOdozp
"""

legs=int(input("Enter num of legs:"))
heads=int(input("Enter total heads:"))
flag=False
for cows in range(0,heads+1):
    hens=heads-cows
    cal_legs=cows*4 + hens*2
    if cal_legs==legs:
       flag=True
       break
if flag:
     print("Cows",cows)
     print("Hens",hens)
else:
     print("no solution")

import calendar
a = int(input("Enter any year:"))
b=int(input("Enter any month:"))
res=calendar.month(a,b)
print(res)

from datetime import date
a=date(2006,2,26)
b=date(2026,4,28)
print("No of days he lived :",b-a)

for i in range(1,5):
  for j in range(i+1):
    print("hi",end="")
  print()

for i in range(10):
    print("*",end=" ")
print()
for i in range(10):
    print("*                 *")

for i in range(10):
    print("*",end=" ")
print()

a=int(input("Enter any number: "))
if a%2==0:
    for i in range(1,11):
        print("{} X  {} = {}".format(i,a,i*a))
else:
     for i in range(1,a+1):
        print("{} X  {} = {}".format(i,a,i*a))

import random
p1=input("Enter player1:")
p2=input("Enter player2:")
s1=10
s2=10
d1=random.randint(1,10)
d2=random.randint(1,10)
print("------------PLAYER1 TURN-----------")
while (True):
    try:
        g1=int(input("Enter your guess: "))
        break
    except ValueError:
        print("Invalid input. Please enter a number.")
s1=s1-1
if g1==d1:
    pass # No need to break, already handled by try-except
print("------------PLAYER2 TURN-----------")
while (True):
    try:
        g2=int(input("Enter your guess: "))
        break
    except ValueError:
        print("Invalid input. Please enter a number.")
s2=s2-1
if g2==d2:
    pass # No need to break, already handled by try-except

print("------------SUMMARY-----------")
print("{}:{}".format(p1,s1))
print("{}:{}".format(p2,s2))
print("-------------------------")
if s1>s2:
    print("Winner is",p1)
elif s2>s1:
    print("Winner is",p2)
else:
    print("Draw")

a=2
for i in range(2,5):
  a=a+2
  for j in range(4):
    a=a+3
  print(a)

a=10
for i in range(4):
  for j in range(i+1):
    a=a+i
  print("ACE")
print(a)

for i in range(100, 1000):
    count = 0
    # Check for divisibility from 1 up to the number itself
    for j in range(1, i + 1):
        if i % j == 0:
            count += 1
    # A prime number has exactly two divisors: 1 and itself
    if count == 2:
        print(f"{i} is a prime number")