# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U5ynxlaxK7JV9PNbU30lxWpT-SbOdozp
"""

legs=int(input("Enter num of legs:"))
heads=int(input("Enter total heads:"))
flag=False
for cows in range(0,heads+1):
    hens=heads-cows
    cal_legs=cows*4 + hens*2
    if cal_legs==legs:
       flag=True
       break
if flag:
     print("Cows",cows)
     print("Hens",hens)
else:
     print("no solution")

import calendar
a = int(input("Enter any year:"))
b=int(input("Enter any month:"))
res=calendar.month(a,b)
print(res)

from datetime import date
a=date(2006,2,26)
b=date(2026,4,28)
print("No of days he lived :",b-a)

for i in range(1,5):
  for j in range(i+1):
    print("hi",end="")
  print()

for i in range(10):
    print("*",end=" ")
print()
for i in range(10):
    print("*                 *")

for i in range(10):
    print("*",end=" ")
print()

a=int(input("Enter any number: "))
if a%2==0:
    for i in range(1,11):
        print("{} X  {} = {}".format(i,a,i*a))
else:
     for i in range(1,a+1):
        print("{} X  {} = {}".format(i,a,i*a))

import random
p1=input("Enter player1:")
p2=input("Enter player2:")
s1=10
s2=10
d1=random.randint(1,10)
d2=random.randint(1,10)
print("------------PLAYER1 TURN-----------")
while (True):
    try:
        g1=int(input("Enter your guess: "))
        break
    except ValueError:
        print("Invalid input. Please enter a number.")
s1=s1-1
if g1==d1:
    pass # No need to break, already handled by try-except
print("------------PLAYER2 TURN-----------")
while (True):
    try:
        g2=int(input("Enter your guess: "))
        break
    except ValueError:
        print("Invalid input. Please enter a number.")
s2=s2-1
if g2==d2:
    pass # No need to break, already handled by try-except

print("------------SUMMARY-----------")
print("{}:{}".format(p1,s1))
print("{}:{}".format(p2,s2))
print("-------------------------")
if s1>s2:
    print("Winner is",p1)
elif s2>s1:
    print("Winner is",p2)
else:
    print("Draw")

a=2
for i in range(2,5):
  a=a+2
  for j in range(4):
    a=a+3
  print(a)

a=10
for i in range(4):
  for j in range(i+1):
    a=a+i
  print("ACE")
print(a)

for i in range(100, 1000):
    count = 0
    # Check for divisibility from 1 up to the number itself
    for j in range(1, i + 1):
        if i % j == 0:
            count += 1
    # A prime number has exactly two divisors: 1 and itself
    if count == 2:
        print(f"{i} is a prime number")


a="*"
b=a.isdigit()
c=a.isalpha()
d=a.isalnum()
print(d)




a="JAI SRH"
b="".join(i for i in a if i in "AEIOU")
print(b)





a="abhinav789456123"
b=sorted(a)
print(b)



 a=input("Enter your pasasword:")
 up=0
 sm=0
 sp=0
 dg=0
 if len(a)>7:
  for i in a:
    if i.isupper():
      up=up+1
    elif i.islower():
      sm=sm+1
    elif i.isdigit():
      dg=dg+1
    else:
      sp=sp+1
  if up>0 and sm>0 and dg>0 and sp>0:
    print("STRONG")
  else:
    print("WEAK")
else:
  print("RETYPE")





import time
import sys
h=3
m=43
s=0
while True:
  sys.stdout.write("\r{:02d}:{:02d}:{:02d}".format(h, m, s))
  sys.stdout.flush()
  time.sleep(1)
  s=s+1
  if s==60:
    s=0
    m=m+1
    if m==60:
      m=0
      h=h+1
      if h==24:
        h=0



from datetime import datetime
import pytz
a=pytz.timezone("Asia/Kolkata")
b=datetime.now(a)
print(b)
for i in pytz.all_timezones:
  print(i)




print(ord(""))


a=[chr (i)for i in range(65,91) if chr(i) not in "AEIOU"]
print(a)



a=6789
b=[int(i) for i in str(a)]
print(max(b))




names=["Ram","Raj","Rose","Jack","Pavi"]
marks=[45,33,90,27,78]
pos=1
for i in range(5):
  if marks[i]>40:
    print("{}.{} has scored{}%".format(pos,names[i],marks[i]))
    pos=pos+1




from os import name
names=["raM","RAJ","rose","JaCk","PaVi"]
marks=[[30,40,50],[66,77,55],[33,78,90],[87,97,57],[47,38,44]]
for i in range(5):
  p=sum(marks[i])//3
  if p>80:
    g="S"
  elif p>40 and p<60:
    g="B"
  else:
    g="A"
  print("{}.Mr/Mrs{} has scored {}% - {} Grade".format(i+1, names[i], p, g))





names=["raM","RAJ","rose","JaCk","PaVi"]
marks=[45,33,90,27,78]
res=list(zip(marks,names))
res1=sorted(res)
pos=1
for i in res1:
  print("Rank {}: {} score is {}".format(pos,i[1],i[0]))
  pos=pos+1





from typing import Collection
a=int(input("Enter num of teams: "))
teams=[]
print("Enter all teams name: ")
for i in range(a):
  t=input("Enter team name: ")
  teams.append(t)
m=int(input("Enter num of meet btw teams: "))

matches=[]
for i in range(0,a-1):
  for j in range(i+1,a):
    for k in range(m):
      matches.append((teams[i],teams[j]))
random.shuffle(matches)
pos=1
for i in matches:
  print("MATCH {} : {} vs {} ".format(pos,i[0],i[1]))
  pos=pos+1




a=input("Enter cute boy name: ")
b=input("Enter avg girl name: ")
a1=list(a)
b1=list(b)
for i in range(len(a1)):
  for j in range(len(b1)):
    if a1[i]==b1[j]:
      a1[i]='2'

      b1[j]='2'
print(a1)
print(b1)
cnt=0
for i in a1:
  if i!='2':
    cnt=cnt+1
print(cnt)
index=0
res=list("FLAMES")
for i in range(5):
  index=(index+ (cnt-1))%len(res)
  res.pop(index)
print(res[0])



def runningSum(nums: list[int]) -> list[int]:
    running_sum_array = []
    current_sum = 0
    for num in nums:
        current_sum += num
        running_sum_array.append(current_sum)
    return running_sum_array



nums1 = [1, 2, 3, 4]
output1 = runningSum(nums1)
print(f"Input: {nums1}, Output: {output1}")


nums2 = [1, 1, 1, 1, 1]
output2 = runningSum(nums2)
print(f"Input: {nums2}, Output: {output2}")


nums3 = [3, 1, 2, 10, 1]
output3 = runningSum(nums3)
print(f"Input: {nums3}, Output: {output3}")




a=[[" " for i in range(11)] for i  in range(11)]

for i in range(11):
  for j in range(11):
    if j==0 or j==10:
      a[i][j]="*"
    if i==j and i<6:
      a[i][j]="*"
    if i+j==10 and i<6:
      a[i][j]="*"

for row in a:
  print("".join(row))




 a={}
 print(type(a))


a=set()
print(type(a))



a={2,2,3,4,5,6,5,6}
for i in a:
  print("Hi")



a={2,4,6,7,8,9}
b={1,2,3,4,5,6,8,9}
print(a.union(b))
print(a&b)


d={'name':'Gill','age':45,'runs':2000}
for i in d.items():
  print(i)
for i in d.keys():
  print(i)



a=int(input("Ishitha Enter any num: "))
nums=[]
while(True):
  if a==1:
    break
  elif a in nums:
    break
  else:
    nums.append(a)
    d=sum([int(i) * int(i) for i in str(a)])
    nums.append(d)
    a = d
if a==1:
  print("Round")
else:
  print("No")








          
